name: Build LazyLoot

env:
  plugin_name: LazyLoot
  repo: FFXIV-LazyLoot

on:
  workflow_dispatch:
  push:
  pull_request:
  
jobs:
    build-LazyLoot:
      name: Build LazyLoot
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2

        - name: Set up .NET
          uses: actions/setup-dotnet@v1
          with:
             dotnet-version: 7.0.x
             
        - name: Restore Dependencies
          run: dotnet restore
          
        - name: Download Dalamud
          run: |
            Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
            Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"

        - name: Build Plugin
          run: |
           invoke-expression 'dotnet build --no-restore --configuration Release LazyLoot'
           
        - name: Rename manifest
          run: Rename-Item -Path .\${{ env.plugin_name }}\bin\Release\${{ env.plugin_name }}\${{ env.plugin_name }}.json -NewName manifest.json

        - name: Upload Artifact
          uses: actions/upload-artifact@v3
          with:
            path: .\${{ env.plugin_name }}\bin\Release\${{ env.plugin_name }}\
            
    release:
        name: release-LazyLoot
        needs: build-LazyLoot
        if: success() && startsWith(github.ref, 'refs/tags/v')
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v3

          - name: Download Build Artifact
            uses: actions/download-artifact@v3

          - name: Extract release notes
            id: extract-release-notes
            uses: ffurrer2/extract-release-notes@v1

          - name: Release
            uses: softprops/action-gh-release@v1
            with:
              name: ${{ github.ref_name }}
              body: ${{ steps.extract-release-notes.outputs.release_notes }}
              files: artifact/*

         
