name: Build Plugin

env:
  plugin_name: LazyLoot

on:
 workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: [windows-2022]

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1.1
        with:
          vs-prerelease: true
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Restore NuGet Packages
        run: nuget restore LazyLoot.sln

      - name: Download Dalamud
        if: "!contains(github.event.head_commit.message, '[stg]')"
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"
      - name: Download Dalamud staging
        if: "contains(github.event.head_commit.message, '[stg]')"
        run: |
            Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
            Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"
            
      - name: Build
        run: dotnet build -c Release -clp:NoSummary

      - name: Rename manifest
        run: mv bin/${{ env.plugin_name }}/${{ env.plugin_name }}.json bin/${{ env.plugin_name }}/manifest.json

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          path: bin/${{ env.plugin_name }}/*
